version: '3'

services:

    php:
        container_name: php
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - appdata:/var/www
            #- ./magento24/app:/var/www/magento24/app:delegated
            #- ./magento24/composer.json:/var/www/magento24/composer.json:delegated
            #- ./magento24/composer.lock:/var/www/magento24/composer.lock:delegated
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=magento24"
 
    nginx:
        container_name: nginx
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ./magento24:/var/www/magento24:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/m2-config/nginx.conf:/var/www/nginx.conf
        depends_on:
            - php
 
    db:
        container_name: mariadb
        image: mariadb:10.4
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            "discovery.type": "single-node"

volumes:
    appdata:
